server:
  port: 8001
spring:
  application:
    name: profile-masster-service

cloud:
  aws:
    sqs:
      endpoint: sqs.ap-southeast-1.amazonaws.com


app:
  feature-config:
    useDynamoDb: true






